# Самостоятельная работа

Практическая работа позволяет систематезировать знания, полученные при изучении языка Python. В частности, данный практический кейс охватывает следующие разделы:

* ввод/вывод данных в программе; 
* структура данных;
* списки;
* условные операторы;
* цикл for;
* функции.

Данное задание погружает нас в Мир начинающего data scientist. Это первая возможность ощутить себя исследователем данных. Предполагается, что Вы имеете дело с готовым набором данных. Набор данных прошёл предварительную обработку и нет необходимости тратить на это время. Вы готовы? Тогда начнём!

Условно, всю практику можно разбить на несколько логических блоков, которые позволяют упростить работу с данными. Мы будем обрабатывать набор данных, связанных со списком самых популярных американских комедий по версии сайта Кинопоиск за определённый период времени. Для каждого фильма известны следующие данные:

* Название фильма;
* Год выхода фильма;
* Рейтинг по версии сайта Кинопоиск;
* Длительность фильма (мин.);
* Бюджет фильма (млн. долларов США);
* Кассовые сборы (млн. долларов США).

## Цель нашего исследовательского анализа:

Необходимо проанализировать полученный датасет, рассчитать некоторые статистические показатели, выявить закономерности и сделать выводы.

## Задачи:

1) Написать функцию, которая позволяет определить сумма всех бюджетов фильмов и кассовых сборов за выбранный период времени.

2) Написать функцию, которая позволяет рассчитать среднее значение бюджетов фильмов и кассовых сборов за выбранный период времени.

3) Написать функцию для расчёта стоимости одной минуты фильма, исходя из потраченного бюджета на фильм. Добавить полученное значение к исходному датасету в виде нового столбца и сохранить как новый датасет new_films.

4) Отсортируйте новый датасет new_films. Выведите новую таблицу данных на экран.

## Анализ данных

In [2]:
films = [
    ['Назад в будущее', 1985, 8.6, 116, ['фантастика', 'комедия'], 19.0, 381.1],
    ['Назад в будущее 2', 1989, 8.3, 108, ['фантастика', 'приключения'], 40.0, 331.9],
    ['Малыш', 1921, 8.2, 68, ['драма', 'комедия'], 0.25, 5.45],
    ['Один дома', 1990, 8.2, 103, ['семейный', 'комедия'], 18.0, 476.68],
    ['Один дома 2: Затерянный в Нью-Йорке', 1992, 7.9, 119, ['семейный', 'комедия'], 18.0, 358.9],
    ['Большой', 1988, 7.9, 104, ['фэнтези', 'мелодрама'], 18.0, 151.6],
    ['Рыжий пёс', 2011, 7.7, 92, ['драма', 'мелодрама', 'комедия'], 8.5, 21.18],
    ['Марли и я', 2008, 7.8, 115, ['драма', 'комедия'], 60.0, 255.7],
    ['Миссис Даутфайр', 1993, 7.7, 125, ['драма', 'комедия'], 25.0, 441.28],
    ['Кудряшка Сью', 1991, 7.6, 101, ['семейный', 'комедия'], 25.0, 33.6]
]

In [3]:
print('Название фильма                     | Год  | Рейтинг | Длина | Бюджет | Сборы  |')
print('--------------------------------------------------------------------------------')
for row in films[:]:
    print('{: <35} | {} | {: >7.2f} | {: >5} | {: >6.1f} | {: >6.1f} |'.format(
        row[0], row[1], row[2], row[3], row[5], row[6]))

Название фильма                     | Год  | Рейтинг | Длина | Бюджет | Сборы  |
--------------------------------------------------------------------------------
Назад в будущее                     | 1985 |    8.60 |   116 |   19.0 |  381.1 |
Назад в будущее 2                   | 1989 |    8.30 |   108 |   40.0 |  331.9 |
Малыш                               | 1921 |    8.20 |    68 |    0.2 |    5.5 |
Один дома                           | 1990 |    8.20 |   103 |   18.0 |  476.7 |
Один дома 2: Затерянный в Нью-Йорке | 1992 |    7.90 |   119 |   18.0 |  358.9 |
Большой                             | 1988 |    7.90 |   104 |   18.0 |  151.6 |
Рыжий пёс                           | 2011 |    7.70 |    92 |    8.5 |   21.2 |
Марли и я                           | 2008 |    7.80 |   115 |   60.0 |  255.7 |
Миссис Даутфайр                     | 1993 |    7.70 |   125 |   25.0 |  441.3 |
Кудряшка Сью                        | 1991 |    7.60 |   101 |   25.0 |   33.6 |

## Сортировка данных

In [3]:
films.sort(key=lambda i: i[1], reverse=True)

print('Название фильма                     | Год  | Рейтинг | Длина | Бюджет | Сборы  |')
print('--------------------------------------------------------------------------------')
for row in films[:]:
    print('{: <35} | {} | {: >7.2f} | {: >5} | {: >6.1f} | {: >6.1f} |'.format(
        row[0], row[1], row[2], row[3], row[5], row[6]))

Название фильма                     | Год  | Рейтинг | Длина | Бюджет | Сборы  |
--------------------------------------------------------------------------------
Рыжий пёс                           | 2011 |    7.70 |    92 |    8.5 |   21.2 |
Марли и я                           | 2008 |    7.80 |   115 |   60.0 |  255.7 |
Миссис Даутфайр                     | 1993 |    7.70 |   125 |   25.0 |  441.3 |
Один дома 2: Затерянный в Нью-Йорке | 1992 |    7.90 |   119 |   18.0 |  358.9 |
Кудряшка Сью                        | 1991 |    7.60 |   101 |   25.0 |   33.6 |
Один дома                           | 1990 |    8.20 |   103 |   18.0 |  476.7 |
Назад в будущее 2                   | 1989 |    8.30 |   108 |   40.0 |  331.9 |
Большой                             | 1988 |    7.90 |   104 |   18.0 |  151.6 |
Назад в будущее                     | 1985 |    8.60 |   116 |   19.0 |  381.1 |
Малыш                               | 1921 |    8.20 |    68 |    0.2 |    5.5 |

## 1. Задача

In [9]:
start_year = 1900
end_year = 2020

def column_sum(films, column, start_year, end_year):
    result = 0
    for row in films:
        if start_year <= row[1] <= end_year:
            result += row[column]
    return result
column = 5                        # 5 - бюджет, 6 - кассовый сбор
print(column_sum(films, column, start_year, end_year))

231.75

## 2. Задача

## 3. Задача

## 4. Задача

## 5. Задача*

А теперь попробуйте самостоятельно выполнить сложную задачу. Задача является объеднинением всего того, чего было выполнено на практике. Напишите функцию для расчёта стоимости одной минуты фильма, исходя из кассовых сборов фильма. Добавьте полученное значение к исходному датасету в виде нового столбца и сохраните как новый датасет new_films_2. Выведите полученную таблицу на экран.

## Выводы по анализу данных.

1) Мы научились загружать датасеты в виде совокупности списков, изменять их и добавлять значения к уже существующим.

2) Смогли определить суммарный бюджет всех фильмов и сумму всех кассовых сборов американских комедийных фильмов из ТОП-10 по версии сайта Кинопоиск: ________.

3) Установили, что самый дорогой фильм по стоимости минуты является фильм "_________" _____ года выпуска.

4) Рассчитали показатель того, сколько денег позволила заработать создателям одна минута фильма.

Отлично! Прекрасная тренировка для начинающего исследователя. Так держать! Дальше будет интереснее. Мы познакомимся с методами визуализации данных, научимся строить различные графики, выявлять сущности и выдвигать предположения. У Вас всё обязательно получится.

## Рекомендации (bread crumbs)

Напоследок сохраните себе несколько полезных материалов, которые позволят быстро вспомнить пройденный материал.

Дополнительная литература

<a href="https://yadi.sk/i/2IrZwWbVSDe_7w">Книга по Python - 1</a>

<a href="https://yadi.sk/i/_QpFM14q9mNZZw">Книга по Python - 2</a>

Справка для работы с типами данных

<a href="https://yadi.sk/i/UgvCmx34Zg8WRA">Справка типы данных</a>

Пишем красивый код

<a href="https://yadi.sk/i/3weLK8W38q1CGA">Правила оформления кода в Python</a>